---
title: thumbs up blogdown!
author: David
date: '2017-08-03'
slug: thumbs-up-blogdown
categories:
  - hello world
tags: []
bigimg: [{src: "/img/DSCI0172.jpg", desc: "Triangle"}]
---


## Hello world post

A lot of times I talk to friends and colleagues about the process of finding out new interesting material, project ideas, cool visualisations or just programming language tricks'n'tips in general and the majority of time the source of these things are people's blogs. Additionally twitter and the #rstats hashtag are a major source as well but I find it is generally just a medium to actual blog posts.  

The idea of having your own blog is kinda scary or intimidating at first, because of the immediate thoughts that comes up - "What will i write about?" or "I am not good enough or the stuff that I do is not interesting enough for someone else to read".  
But there are many, many good reasons for keeping a blog - besides sharing with others what you did and how you did it, which could potentially also help somebody else accomplish some task, to keeping track of stuff for your own sake. I really like the idea that writing blog posts forces one to practice clear, concise thought, and clean and reproducible workflow.  
In the spirit of [this tweet](https://twitter.com/gdequeiroz/status/821766148655968256) from Gabriela de Queiroz - the initiator of #RLadies:  

`r blogdown::shortcode('tweet', '821766148655968256')`

So I decided to try it out for myself and write every now and then about my projects and interests. At first I started with the [Beautiful Jekyll](http://deanattali.com/beautiful-jekyll/) theme by [Dean Atalli](http://deanattali.com/) which was very easy to set up thanks to his great documentation. Although I wasn't sure that I understand the underlying technologies (jekyll, ruby...) and what the assumed underlying structure should be - it worked well and I was able to set it up using github pages.  

Then some months ago I found out about [Yihui Xie's](https://yihui.name/) blogdown package and I loved the idea that all of this is made possible from within R itself! [blogdown](https://github.com/rstudio/blogdown) is truly an amazing package and makes the whole process of setting up your own blog, installing themes etc. so easy. It's pretty cool that people like me who don't know much about html, css, javascript and web development - but can work their way around in R can just download a package and set up a personal blog by calling a couple of functions!  
I think Yihui has contributed pretty amazing stuff to the R world and I really like all of his open-source projects as well as his great ability to use every chance he gets to place somewhere a funny gif :-)  
(if you don't know about this, you have to check out some of his presentations on useR conference or rstudio::conf 2017 or the xaringan package).  
I followed the instructions in the accompanying [blogdown book](https://bookdown.org/yihui/blogdown/workflow.html) and it was pretty straightforward to set up, without ever leaving RStudio.  

Hugo - the work engine underneath the blogdown package offers plethora of themes for the look of your website but I really liked the one from Dean and wanted to stick with it. I was very happy to find out that [Michael Romero](https://github.com/halogenica/beautifulhugo) has ported the theme to Hugo as Beautiful Hugo.  

The last step was to host the website somewhere. As i had already previously set up Beautiful Jekyll to work with github pages - i imagined this would be similarly easy. It turned out that it is not so straightforward to combine blogdown with github pages. The problem lies in the detail that you would have to keep 2 separate repositories - one for the "live" website and another for keeping track of your (unpublished) posts etc. After some hours reading about orphaned master branches and whatnots - I decided to take Yihui's advice and go with [netlify](https://www.netlify.com/). That way I could keep the sources in a github repo and link that to my netlify account which would then automatically rebuild and publish every time I commit some changes. Pretty good deal.  

One last step which I would like to do is to migrate my website to the [rbind](https://support.rbind.io/about/) organisation which is an RStudio initiative to help the community with making, troubleshooting and hosting websites. They offer a free! subdomain of your choice for your website. Many of the blogs I enjoy reading - like for example Rob Hyndmanns's [Hyndsight](https://support.rbind.io/2017/05/15/converting-robjhyndman-to-blogdown/), Romain François's [blog](https://support.rbind.io/2017/05/29/romain-francois-s-site-with-blogdown-hugo-rbind/) and even Yihui Xie's [own website](https://support.rbind.io/2017/04/25/yihui-website/) are there including their experiences with migrating to blogdown. I learned a lot from reading their posts.  

Well, this is more than enough for an initial post. Now that writing them is made a breeze from R - I plan to do this more frequently and on various topics.  

Thanks to the hard work from all the fantastic people and organisations that made this possible and easy.   

